### ISSUE TITLE
Fix Content-Length header

### ISSUE THREAD

**Issue by ajgarlag** [middlewares/minifier#1]
The content-length header should be fixed once the body has been modified.

See https://github.com/middlewares/encoder/issues/1

**Comment by ajgarlag** [comment]
This issue affects to any middleware that modifies the response (or request) body. Maybe, a helper class or method can be added to `middlewares/utils` package to fix this header.

**Comment by oscarotero** [comment]
Yep, it's a good idea.

**Comment by oscarotero** [comment]
v0.3.1 released
