### ISSUE TITLE
Dependency patchwork/jsqueeze is abandoned

### ISSUE THREAD

**Issue by mav2287** [middlewares/minifier#5]
Noticed that the error ``Package patchwork/jsqueeze is abandoned, you should avoid using it. No replacement was suggested.`` comes up when installing with composer. Looks like it a dependency of `wyrihaximus/js-compress` which is dependency of `wyrihaximus/html-compress`.

I checked the `composer.json` file for `WyriHaximus/php-js-compress` and the current version seems to have already replaced `patchwork/jsqueeze` so I'm not sure if this is a version issue, but just wanted to point it out.

**Comment by oscarotero** [comment]
As I can see, this dependency was removed in v2.0 (https://github.com/WyriHaximus/php-js-compress/releases/tag/2.0.0)
html-compress v3 use js-compress v1, and html-compress v4 use js-compress v2 or upper.

Due this package supports html-compress v3 and v4 (in order to support more php versions), this warning is visible only if composer install html-compress v3. So, it depends on your php version, to install one or other version, hence you can see this warning or not.

**Comment by mav2287** [comment]
That makes sense. I am on 7.4.16, so if the min version to not see it php 8?

**Comment by oscarotero** [comment]
You can see the different versions and requirements in packagist.
It looks like js-compress v2 is used from html-compress 4.1.0, but it's compatible with php 7.4:
https://packagist.org/packages/wyrihaximus/html-compress#4.1.0

So I don't know why you are installing php-compress v3, maybe there is due another dependency that blocking this upgrade.

**Comment by mav2287** [comment]
Must be, I just wanted to make sure this was something that was taken care of. I am closing this out since it seems to be specific to my install.

**Comment by mav2287** [comment]
I am re-opening this issue as this is an issue on PHP 8 as well. Even with an empty directory all it takes to reproduce this is to run `composer require middlewares/minifier --ignore-platform-reqs` command.

**Comment by mav2287** [comment]
@oscarotero can you please publish a new release with the current contents of master? That should solve the issue.

The current release was published on Dec 3rd, 2020, but on Dec 24th 2020 the `composer.json` file was updated. The updated `composer.json` doesn't produce this issue, but since there isn't a release that includes it Composer is installing the older one. Creating a new release should solve that issue.

**Comment by oscarotero** [comment]
I just released [2.0.2](https://github.com/middlewares/minifier/releases/tag/v2.0.2). Thanks for advising.
